### ISSUE TITLE
fate_core_with_rolls_VF was merged ok but is not the one on roll20

### ISSUE THREAD

**Issue by sioc-de-narf** [Ramblurr/roll20-character-sheets#3]
fate_core_with_rolls_VF was merged but is not the one on roll20, when i select it in roll20 I get the previous version

**Comment by Ramblurr** [comment]
Just fyi, this is the wrong repo, you need https://github.com/Roll20/roll20-character-sheets

**Comment by sioc-de-narf** [comment]
I've seen, that's why i closed it :) thx
